Realese 1.6.19 - PPM-13
pay-now/paynow-woocommerce pull request #177
Opened 2022-09-05 15:06 UTC by DeveloperMovecloser

2022-09-05 17:10 UTC, emilleszczak2 requested changes

2022-09-05 17:10 UTC, emilleszczak2 commented on src/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php
> +            if ($payment_method === 'pay_by_paynow_pl_pbl') {
Wystwiłbym enuma (PaynowPaymentGateway) ze stałymi i zbudował go z użyciem  WC_PAY_BY_PAYNOW_PL_PLUGIN_PREFIX

2022-09-09 12:16 UTC, DeveloperMovecloser commented on src/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php
> +            if ($payment_method === 'pay_by_paynow_pl_pbl') {
Slugi wyniesione do enuma

2022-09-09 14:33 UTC, emilleszczak2 approved these changes

2022-09-10 09:14 UTC, emilleszczak2 commented on src/includes/abstract/class-wc-gateway-pay-by-paynow-pl.php
> +    public const BLIK_PAYMENT = 0;
Nie lepiej prosty const?
`const BLIK_PAYMENT_GATEWAY = WC_PAY_BY_PAYNOW_PL_PLUGIN_PREFIX. 'blik',`

2022-09-13 14:29 UTC, merged